<?php

return [
    'permissions' => [
        'websocket_*' => 'Umożliwia dostęp do websocket dla tego serwera.',
        'control_console' => 'Pozwala użytkownikowi na wysyłanie danych do konsoli serwera.',
        'control_start' => 'Pozwala użytkownikowi na uruchomienie instancji serwera.',
        'control_stop' => 'Pozwala użytkownikowi na zatrzymanie instancji serwera.',
        'control_restart' => 'Pozwala użytkownikowi na ponowne uruchomienie instancji serwera.',
        'control_kill' => 'Pozwala użytkownikowi na zabicie instancji serwera.',
        'user_create' => 'Pozwala użytkownikowi na tworzenie nowych kont użytkowników dla serwera.',
        'user_read' => 'Zezwala użytkownikowi na przeglądanie użytkowników powiązanych z tym serwerem.',
        'user_update' => 'Pozwala użytkownikowi na modyfikowanie innych użytkowników związanych z tym serwerem.',
        'user_delete' => 'Pozwala użytkownikowi na usunięcie innych użytkowników powiązanych z tym serwerem.',
        'file_create' => 'Zezwala użytkownikowi na tworzenie nowych plików i katalogów.',
        'file_read' => 'Pozwala użytkownikowi na przeglądanie plików i folderów związanych z tą instancją serwera, a także na przeglądanie ich zawartości.',
        'file_update' => 'Pozwala użytkownikowi na aktualizację plików i folderów powiązanych z serwerem.',
        'file_delete' => 'Pozwala użytkownikowi na usuwanie plików i katalogów.',
        'file_archive' => 'Pozwala użytkownikowi na tworzenie archiwów plików i dekompresję istniejących archiwów.',
        'file_sftp' => 'Pozwala użytkownikowi na wykonanie powyższych czynności plikowych za pomocą klienta SFTP.',
        'allocation_read' => 'Umożliwia dostęp do stron zarządzania alokacją serwera.',
        'allocation_update' => 'Zezwala użytkownikowi na dokonywanie modyfikacji alokacji serwera.',
        'database_create' => 'Pozwala użytkownikowi na utworzenie nowej bazy danych dla serwera.',
        'database_read' => 'Zezwala użytkownikowi na przeglądanie baz danych serwera.',
        'database_update' => 'Umożliwia użytkownikowi dokonywanie zmian w bazie danych. Jeśli użytkownik nie posiada uprawnień "Widok Hasła", nie będzie mógł również modyfikować hasła..',
        'database_delete' => 'Zezwala użytkownikowi na usunięcie instancji bazy danych.',
        'database_view_password' => 'Zezwala użytkownikowi na przeglądanie hasła do bazy danych w systemie.',
        'schedule_create' => 'Pozwala użytkownikowi na utworzenie nowego harmonogramu dla serwera.',
        'schedule_read' => 'Zezwala użytkownikowi na przeglądanie harmonogramów dla danego serwera.',
        'schedule_update' => 'Zezwala użytkownikowi na dokonywanie zmian w istniejącym harmonogramie serwera.',
        'schedule_delete' => 'Pozwala użytkownikowi na usunięcie harmonogramu dla serwera.',
    ],
];
